# Generated by Django 3.0.5 on 2020-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
