# Generated by Django 3.0.5 on 2020-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200427_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
