# Generated by Django 3.0.5 on 2020-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200427_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Book', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
