# Generated by Django 3.0.5 on 2020-05-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200504_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
