# Generated by Django 3.0.5 on 2020-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200504_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('cs', 'CSE/IT'), ('mech', 'ME'), ('ece', 'ECE'), ('ee', 'EE')], max_length=5),
        ),
    ]
